version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: zoo_postgres
    restart: always
    environment:
      POSTGRES_USER: zoo_admin
      POSTGRES_PASSWORD: zoo_password
      POSTGRES_DB: zoo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
